window.YH_PART_1=`
<div class="noise"></div><div class="cursor"><span></span></div><div class="scroll-progress"></div>
<div class="menu"><div class="menu-bg-word">YASSERHAUS</div><button class="menu-close" aria-label="إغلاق">×</button><div class="menu-inner"><nav><a href="#about"><span>01</span>من نحن</a><a href="#work"><span>02</span>الأعمال</a><a href="#services"><span>03</span>الخدمات</a><a href="#journal"><span>04</span>المجلة</a><a href="#contact"><span>05</span>تواصل</a></nav><div class="menu-note">استوديو مستقل<br>جدة، السعودية</div></div></div>
<header><div class="wrap nav"><a class="brand" href="#top">ياسرهاوس®</a><nav class="navlinks"><a href="#about">الاستوديو</a><a href="#work">الأعمال</a><a href="#services">الخدمات</a><a href="#faq">الأسئلة</a></nav><div><button class="menu-btn">القائمة</button> <a class="cta" href="#contact">ابدأ مشروعك</a></div></div></header>
<main id="top">
<section class="hero"><div class="kinetic-mark" aria-hidden="true"><div class="km-card"><span>نحوّل</span><b>الفكرة</b><i>إلى أثر</i></div><div class="km-orbit"><span></span><span></span><span></span></div><div class="km-cross">✦</div></div><div class="hero-grid-lines"></div><div class="wrap hero-grid"><div class="hero-copy"><div class="eyebrow"><span class="dot"></span>استوديو إبداعي مستقل</div><h1><span class="hero-line">نصمّم</span><span class="solid-accent hero-line">الحضور</span></h1><p class="hero-sub">استراتيجية، هوية وتجارب رقمية لعلامات تريد أن تُرى، تُفهم، وتُتذكّر.</p></div><div class="hero-media magnetic"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85" alt="استوديو إبداعي"><b>من الفكرة<br>إلى التأثير</b><div class="image-index">01 / 05</div></div></div></section>
<div class="marquee"><div class="track"><span>بناء العلامات</span><span>التجارب الرقمية</span><span>تصميم المنتجات</span><span>الحملات الإبداعية</span><span>بناء العلامات</span><span>التجارب الرقمية</span><span>تصميم المنتجات</span><span>الحملات الإبداعية</span></div></div>
<section class="section" id="about"><div class="wrap"><div class="intro reveal"><span class="kicker">01 — ياسرهاوس</span><div><p class="big">نحن استوديو عربي نبني <span class="pill">علامات</span> حيّة، واضحة، ومصممة لتبقى في الذاكرة.</p><div class="chips"><span class="chip">استراتيجية</span><span class="chip">هوية</span><span class="chip">ويب</span><span class="chip">حملات</span></div></div></div><div class="clients reveal"><div class="client"><b>سَما</b><small>عقار واستثمار</small></div><div class="client"><b>مسار</b><small>أعمال ومشتريات</small></div><div class="client"><b>نواة</b><small>تقنية ومنتجات</small></div><div class="client"><b>مدى</b><small>تطوير حضري</small></div><div class="client"><b>خطوة</b><small>تجارب وفعاليات</small></div></div></div></section>
<section class="section dark" id="work"><div class="wrap"><div class="head reveal"><h2>أعمال<br>مختارة</h2><p>نربط التفكير الاستراتيجي بالتصميم الجريء، ونبني كل مشروع من الفكرة الأساسية حتى أدق نقطة تواصل.</p></div><div class="projects"><article class="project reveal"><img src="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=85" alt="مشروع"><div class="project-info"><h3>هوية نواة</h3><div class="meta"><span>هوية</span><span>رقمي</span></div></div></article><article class="project reveal"><img src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1800&q=85" alt="مشروع"><div class="project-info"><h3>تجربة مدى</h3><div class="meta"><span>مساحات</span><span>تجربة</span></div></div></article><article class="project reveal"><img src="https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1800&q=85" alt="مشروع"><div class="project-info"><h3>إطلاق مسار</h3><div class="meta"><span>استراتيجية</span><span>حملة</span></div></div></article></div></div></section>
`;